[project]
name = "movies-backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.117.1",
    "psycopg-pool>=3.3.3",
    "psycopg[binary]>=3.3.6",
    "pydantic>=2.11.9",
    "pydantic-settings>=2.15.0",
    "sse-starlette>=3.0.3",
]

[tool.fastapi]
entrypoint = "app.main:app"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "pytest-docker>=3.2.5",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
